version: '2'
services:
  db:
    image: mongo:latest
    environment:
      - MONGODB_USER="crawler"
      - MONGODB_DATABASE="crawler"
      - MONGODB_PASS="max"
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles